"use client";
import {useState} from "react";

const copy={
en:{
nav:["Solutions","Our Story","Reporting","Contact"],talk:"LET'S TALK →",lang:"🇪🇸 ES",
ey:"WORKFORCE · SERVICES · OPERATIONS",hero1:"More capacity.",hero2:"Less complexity.",lead:"REMA² helps businesses get the people, crews and field support they need to keep work moving.",workers:"I NEED WORKERS",service:"I NEED A SERVICE",based:"BASED IN WOBURN, MA",area:"SERVING MASSACHUSETTS & NEW HAMPSHIRE",
needPeople:"Need people?",peopleText:"Add reliable capacity when demand changes — from individual labor support to supplemental field crews.",reqWorkers:"REQUEST WORKERS →",needDone:"Need it done?",doneText:"Let REMA² take responsibility for the service, crew coordination and field execution.",reqService:"REQUEST A SERVICE →",
multi:"ONE PARTNER. MULTIPLE SOLUTIONS.",built:"Built around the work you need done.",builtText:"We combine flexible workforce capacity with hands-on field services and operational coordination. One relationship. Multiple ways to support your business.",
services:[["Workforce Solutions","Supplemental crews for recurring operations, workload peaks, special projects and workforce coverage."],["Cleaning Services","Commercial, post-construction, turnover, deep cleaning and recurring cleaning support."],["Construction Support","Field crews for demolition, concrete, site work, general labor and project support."],["Landscape Support","Flexible labor for maintenance, installation, seasonal demand and landscape operations."],["Property Services","Cleanup, exterior maintenance, snow & ice support and recurring field services."],["Project & Operations","Workforce coordination, field documentation, progress tracking and operational support."]],
storyTag:"OUR STORY",storyTitle:"A new company built on proven operating experience.",storyP1:"REMA² was created in Massachusetts, but the operating experience behind it was built over years of managing workforce-intensive businesses and complex field operations in Brazil.",storyP2:"That journey taught us that providing labor is only part of the job. Real value comes from organization, leadership, communication, accountability and visibility.",storyBold:"We brought those lessons to REMA² — adapted for the way businesses work here.",
legacy:"LEADERSHIP EXPERIENCE BEFORE REMA²",stat1:"Workers allocated",stat2:"Clients served",stat3:"Outsourced workforce hours",stat4:"Projects completed",legacyNote:"Historical operating scale from businesses previously led by REMA²'s founder in Brazil. These figures are not REMA² operating results.",
peopleTag:"BEYOND THE NUMBERS",peopleTitle:"People drive results.",peopleText:"Strong operations start with the right people — but they depend on communication, training, engagement, accountability and clear responsibilities to perform consistently.",peopleQuote:"People do the work. Management makes it work.",
reportTag:"REPORTING & VISIBILITY",reportTitle:"Know what's happening. Even when you're not there.",reportText:"Managed REMA² operations can include structured field reporting that gives clients visibility into people, progress, quality and issues in the field.",reportItems:["Work completed & progress","Photo documentation","Crew & activity records","Issues & pending items","Site & material observations","Next steps"],sample:"FIELD REPORT / SAMPLE",today:"TODAY'S OPERATION",crew:"Crew",attendance:"Attendance",progress:"Progress",issues:"Open issues",safety:"Safety incidents",photos:"Photos",
approach:"THE REMA² APPROACH",principles:[["Responsive","Built for changing workloads and real-world field demands."],["Accountable","Clear communication, coordination and ownership of the work."],["Scalable","Support that can expand or contract as your operation requires."]],
contactTag:"LET'S GET TO WORK",contactTitle:"Tell us what you need.",contactText:"Workers for tomorrow, a crew for an ongoing account, or a service you need executed — start with REMA².",footer:"Workforce · Services · Operations",rights:"All rights reserved."
},
es:{
nav:["Soluciones","Nuestra Historia","Reportes","Contacto"],talk:"HABLEMOS →",lang:"🇺🇸 EN",
ey:"PERSONAL · SERVICIOS · OPERACIONES",hero1:"Más capacidad.",hero2:"Menos complejidad.",lead:"REMA² ayuda a las empresas a contar con las personas, los equipos y el soporte de campo que necesitan para mantener el trabajo en marcha.",workers:"NECESITO PERSONAL",service:"NECESITO UN SERVICIO",based:"SEDE EN WOBURN, MA",area:"SERVICIO EN MASSACHUSETTS Y NEW HAMPSHIRE",
needPeople:"¿Necesita personal?",peopleText:"Aumente su capacidad cuando cambie la demanda, desde apoyo individual hasta equipos complementarios de campo.",reqWorkers:"SOLICITAR PERSONAL →",needDone:"¿Necesita resolverlo?",doneText:"Deje que REMA² asuma la responsabilidad del servicio, la coordinación del equipo y la ejecución en campo.",reqService:"SOLICITAR SERVICIO →",
multi:"UN SOCIO. MÚLTIPLES SOLUCIONES.",built:"Nos adaptamos al trabajo que necesita realizar.",builtText:"Combinamos capacidad flexible de personal con servicios de campo y coordinación operativa. Una sola relación. Múltiples formas de apoyar a su empresa.",
services:[["Soluciones de Personal","Equipos complementarios para operaciones recurrentes, picos de trabajo, proyectos especiales y cobertura de personal."],["Servicios de Limpieza","Limpieza comercial, post-construcción, cambios de ocupación, limpieza profunda y soporte recurrente."],["Soporte de Construcción","Equipos de campo para demolición, concreto, obra, mano de obra general y apoyo a proyectos."],["Soporte de Landscaping","Personal flexible para mantenimiento, instalación, demanda estacional y operaciones de landscaping."],["Servicios de Propiedad","Limpieza exterior, mantenimiento, nieve y hielo y servicios de campo recurrentes."],["Proyectos y Operaciones","Coordinación de personal, documentación de campo, seguimiento de avance y soporte operativo."]],
storyTag:"NUESTRA HISTORIA",storyTitle:"Una nueva empresa respaldada por experiencia operativa comprobada.",storyP1:"REMA² nació en Massachusetts, pero la experiencia operativa que la respalda se construyó durante años gestionando empresas intensivas en personal y operaciones de campo complejas en Brasil.",storyP2:"Ese recorrido nos enseñó que proveer mano de obra es solo una parte del trabajo. El verdadero valor está en la organización, liderazgo, comunicación, responsabilidad y visibilidad.",storyBold:"Trajimos esas lecciones a REMA² — adaptadas a la forma de trabajar de las empresas aquí.",
legacy:"EXPERIENCIA DE LIDERAZGO ANTES DE REMA²",stat1:"Trabajadores asignados",stat2:"Clientes atendidos",stat3:"Horas de trabajo tercerizado",stat4:"Proyectos completados",legacyNote:"Escala operativa histórica de empresas anteriormente lideradas por el fundador de REMA² en Brasil. Estas cifras no son resultados operativos de REMA².",
peopleTag:"MÁS ALLÁ DE LOS NÚMEROS",peopleTitle:"Las personas generan resultados.",peopleText:"Las buenas operaciones comienzan con las personas correctas, pero dependen de comunicación, capacitación, compromiso, responsabilidad y funciones claras.",peopleQuote:"Las personas hacen el trabajo. La gestión hace que funcione.",
reportTag:"REPORTES Y VISIBILIDAD",reportTitle:"Sepa qué está pasando. Incluso cuando no está allí.",reportText:"Las operaciones gestionadas por REMA² pueden incluir reportes estructurados de campo que dan visibilidad sobre personas, progreso, calidad y problemas.",reportItems:["Trabajo realizado y avance","Documentación fotográfica","Registros de equipo y actividad","Problemas y pendientes","Observaciones de obra y materiales","Próximos pasos"],sample:"REPORTE DE CAMPO / EJEMPLO",today:"OPERACIÓN DE HOY",crew:"Equipo",attendance:"Asistencia",progress:"Avance",issues:"Pendientes",safety:"Incidentes de seguridad",photos:"Fotos",
approach:"EL ENFOQUE REMA²",principles:[["Ágil","Preparados para cargas variables y exigencias reales del trabajo de campo."],["Responsable","Comunicación clara, coordinación y responsabilidad por el trabajo."],["Escalable","Soporte que crece o se ajusta según las necesidades de su operación."]],
contactTag:"MANOS A LA OBRA",contactTitle:"Díganos qué necesita.",contactText:"Personal para mañana, un equipo para una cuenta recurrente o un servicio que necesita ejecutar — comience con REMA².",footer:"Personal · Servicios · Operaciones",rights:"Todos los derechos reservados."
}};

export default function Home(){const[lang,setLang]=useState("en");const t=copy[lang];return <main>
<header><a className="brand" href="#">REMA<sup>2</sup><span>GROUP</span></a><nav><a href="#solutions">{t.nav[0]}</a><a href="#story">{t.nav[1]}</a><a href="#reporting">{t.nav[2]}</a><a href="#contact">{t.nav[3]}</a></nav><div className="headerRight"><button className="lang" onClick={()=>setLang(lang==="en"?"es":"en")}>{t.lang}</button><a className="headerCta" href="#contact">{t.talk}</a></div></header>
<section className="hero"><div><div className="eyebrow">{t.ey}</div><h1>{t.hero1}<br/><em>{t.hero2}</em></h1><p className="heroLead">{t.lead}</p><div className="actions"><a className="primary" href={"mailto:hello@rema2.com?subject="+t.workers}>{t.workers} →</a><a className="secondary" href={"mailto:hello@rema2.com?subject="+t.service}>{t.service}</a></div></div><div className="heroBottom"><span>{t.based}</span><span>•</span><span>{t.area}</span></div></section>
<section className="choice"><div className="choiceCard dark"><span className="tag">01 / WORKFORCE</span><h2>{t.needPeople}</h2><p>{t.peopleText}</p><a href="#contact">{t.reqWorkers}</a></div><div className="choiceCard light"><span className="tag">02 / SERVICES</span><h2>{t.needDone}</h2><p>{t.doneText}</p><a href="#contact">{t.reqService}</a></div></section>
<section className="intro" id="solutions"><div><div className="eyebrow">{t.multi}</div><h2>{t.built}</h2></div><p>{t.builtText}</p></section>
<section className="grid">{t.services.map((s,i)=><article key={s[0]}><b>0{i+1}</b><h3>{s[0]}</h3><p>{s[1]}</p><a href="#contact">EXPLORE →</a></article>)}</section>
<section className="story" id="story"><div className="storyHead"><div className="eyebrow">{t.storyTag}</div><h2>{t.storyTitle}</h2></div><div className="storyCopy"><p>{t.storyP1}</p><p>{t.storyP2}</p><strong>{t.storyBold}</strong></div></section>
<section className="legacy"><div className="eyebrow">{t.legacy}</div><div className="legacyStats"><div><strong>1,400+</strong><span>{t.stat1}</span></div><div><strong>200+</strong><span>{t.stat2}</span></div><div><strong>5M+</strong><span>{t.stat3}</span></div><div><strong>1,900+</strong><span>{t.stat4}</span></div></div><p className="legacyNote">{t.legacyNote}</p></section>
<section className="people"><div><div className="eyebrow">{t.peopleTag}</div><h2>{t.peopleTitle}</h2><p>{t.peopleText}</p></div><blockquote>{t.peopleQuote}</blockquote></section>
<section className="reporting" id="reporting"><div className="reportCopy"><div className="eyebrow">{t.reportTag}</div><h2>{t.reportTitle}</h2><p>{t.reportText}</p><div className="reportList">{t.reportItems.map(x=><span key={x}>✓ {x}</span>)}</div></div><div className="reportCard"><div className="reportTop"><span>REMA²</span><small>{t.sample}</small></div><h3>{t.today}</h3><div className="metric"><span>{t.crew}</span><b>8</b></div><div className="metric"><span>{t.attendance}</span><b>100%</b></div><div className="metric"><span>{t.progress}</span><b>92%</b></div><div className="metric"><span>{t.issues}</span><b>1</b></div><div className="metric"><span>{t.safety}</span><b>0</b></div><div className="metric"><span>{t.photos}</span><b>12</b></div></div></section>
<section className="principles"><div className="eyebrow">{t.approach}</div><div className="principleGrid">{t.principles.map((p,i)=><div key={p[0]}><b>0{i+1}</b><h3>{p[0]}</h3><p>{p[1]}</p></div>)}</div></section>
<section className="cta" id="contact"><div className="eyebrow">{t.contactTag}</div><h2>{t.contactTitle}</h2><p>{t.contactText}</p><div className="actions"><a className="primary black" href={"mailto:hello@rema2.com?subject="+t.workers}>{t.reqWorkers}</a><a className="secondary darkBorder" href={"mailto:hello@rema2.com?subject="+t.service}>{t.reqService}</a></div><a className="email" href="mailto:hello@rema2.com">hello@rema2.com</a></section>
<footer><a className="brand" href="#">REMA<sup>2</sup><span>GROUP</span></a><p>{t.footer}<br/>Woburn, Massachusetts<br/>{t.area}</p><p><a href="mailto:hello@rema2.com">hello@rema2.com</a><br/><a href="tel:+19786487729">(978) 648-7729</a></p><small>© 2026 REMA² Group. {t.rights}</small></footer>
</main>}