const services=[
["Workforce Solutions","Flexible supplemental crews for recurring operations, workload peaks, special projects and workforce coverage."],
["Cleaning Services","Commercial, post-construction, turnover, deep cleaning and recurring cleaning support."],
["Construction Support","Reliable field crews for demolition, concrete, site work, general labor and project support."],
["Landscape Support","Flexible labor for maintenance, installation, seasonal demand and landscape operations."],
["Property Services","Cleanup, exterior maintenance, snow & ice support and recurring field services."],
["Project & Operations Support","Workforce coordination, field documentation, progress tracking and operational support."]
];
export default function Home(){return <main>
<header><a className="brand" href="#">REMA<sup>2</sup><span>GROUP</span></a><nav><a href="#solutions">Solutions</a><a href="#about">About</a><a href="#work">Experience</a><a href="#contact">Contact</a></nav><a className="smallCta" href="#contact">REQUEST A QUOTE</a></header>
<section className="hero"><div className="eyebrow">WORKFORCE · SERVICES · OPERATIONS</div><h1>The workforce to<br/><em>get the job done.</em></h1><p>Managed workforce and field-service solutions that help businesses expand capacity, cover workforce gaps and execute projects without unnecessary operational complexity.</p><div className="actions"><a className="primary" href="#contact">REQUEST WORKERS →</a><a className="secondary" href="#contact">REQUEST A SERVICE</a></div><div className="region">WOBURN, MASSACHUSETTS <span>•</span> SERVING MA & NH</div></section>
<section className="intro" id="solutions"><div><div className="eyebrow">ONE PARTNER. MULTIPLE SOLUTIONS.</div><h2>Built around the work<br/>you need done.</h2></div><p>REMA² combines flexible workforce capacity with hands-on field services and operational coordination. One relationship. Multiple ways to support your business.</p></section>
<section className="grid">{services.map((s,i)=><article key={s[0]}><b>0{i+1}</b><h3>{s[0]}</h3><p>{s[1]}</p><a href="#contact">LEARN MORE →</a></article>)}</section>
<section className="scale" id="about"><div className="eyebrow">BUILT TO SCALE WITH YOUR BUSINESS</div><h2>Your workload changes.<br/><em>Your workforce should too.</em></h2><p>From a few additional workers to a complete supplemental crew, REMA² helps businesses increase field capacity without carrying the full operational burden of permanent expansion.</p><strong>We don't simply connect companies with workers. We help mobilize and manage the workforce needed to perform the work.</strong></section>
<section className="proof" id="work"><div><div className="eyebrow">OPERATIONAL EXPERIENCE</div><h2>Management experience<br/>that scales.</h2></div><div className="stats"><div><strong>500+</strong><span>Permanent workforce managed</span></div><div><strong>200+</strong><span>Temporary workers at peak</span></div><div><strong>100+</strong><span>Worker rapid mobilizations</span></div></div></section>
<section className="cta" id="contact"><div className="eyebrow">LET'S GET TO WORK</div><h2>Need more people?<br/>Need the job done?</h2><p>Tell us what you need. We'll help determine the right crew, service or operational solution.</p><div className="actions"><a className="primary light" href="mailto:hello@rema2.com?subject=Workforce Request">REQUEST WORKERS →</a><a className="secondary lightBorder" href="mailto:hello@rema2.com?subject=Service Request">REQUEST A SERVICE</a></div></section>
<footer><a className="brand" href="#">REMA<sup>2</sup><span>GROUP</span></a><p>Workforce · Services · Operations<br/>Massachusetts & New Hampshire</p><p><a href="mailto:hello@rema2.com">hello@rema2.com</a><br/><a href="tel:+19786487729">(978) 648-7729</a></p><small>© 2026 REMA² Group. All rights reserved.</small></footer>
</main>}