export const servicePages = {
  "construction-support": {
    name: "Construction Support",
    title: "Construction Support in MA & NH | REMA² Group",
    description: "Construction support, general labor and field crews for contractors in Massachusetts and New Hampshire. Discuss demolition, concrete, site work and project needs.",
    headline: "Construction support.", accent: "Keep your project moving.",
    lead: "REMA² supports contractors and businesses with field crews, general labor and coordinated project support in Massachusetts and New Hampshire. Based in Woburn, MA, we help you define the people and field work your project needs.",
    scopeTitle: "Support around the work on site.",
    scopeIntro: "A useful construction request starts with the tasks, site conditions and project schedule. Tell us which part of the work needs support so we can discuss responsibilities and the appropriate scope.",
    services: [
      ["General labor & supplemental crews", "Add labor capacity for workload peaks, specific project phases or ongoing construction operations. Share the crew size, tasks and experience the assignment requires."],
      ["Demolition support", "Field support for demolition activities within an agreed project scope. Describe the area, materials, site access and coordination requirements when requesting a quote."],
      ["Concrete & site work support", "Crews for concrete-related tasks and site work support. We review the work with you to clarify responsibilities, equipment needs and the project schedule."],
      ["Project & field coordination", "Coordinate people, activities and communication for managed REMA² work. Field documentation and progress reporting can be discussed as part of the scope."],
    ],
    planningTitle: "Help us understand your site.",
    planning: ["Project city and state", "Tasks and phase of construction", "Crew size and expected duration", "Start date and working hours", "Site access, equipment and project requirements"],
    steps: [
      ["Describe the project.", "Tell us the location, work phase, tasks and schedule. Include site conditions and any experience or equipment the assignment requires."],
      ["Agree on the scope.", "We discuss crew availability, responsibilities, coordination and pricing before work is agreed."],
      ["Coordinate the field work.", "Establish communication and responsibilities for the assignment. Discuss documentation and reporting needs for managed REMA² operations."],
    ],
    faqs: [
      ["Do you provide workers or execute construction support services?", "Both approaches can be discussed. Request supplemental workers for your operation, or an agreed construction support service with crew coordination and field execution."],
      ["What construction tasks can I ask about?", "Our construction support includes general labor, demolition, concrete, site work and project support. Describe the exact tasks so we can review the scope and any project requirements."],
      ["Can I request a crew for one phase of a project?", "Yes. Tell us which phase needs support, the number of workers, expected duration and preferred start date. Scheduling depends on the scope and availability discussed with you."],
      ["Where is construction support available?", "REMA² is based in Woburn, Massachusetts, and serves Massachusetts and New Hampshire. Include the site location in your request."],
    ],
    requestTitle: "Discuss your construction project.",
    requestPlaceholder: "Describe the tasks, project phase, crew needs, site conditions and equipment requirements.",
  },
  "cleaning-services": {
    name: "Cleaning Services",
    title: "Commercial & Post-Construction Cleaning in MA & NH | REMA² Group",
    description: "Commercial, post-construction, turnover and recurring cleaning services in Massachusetts and New Hampshire. Request a cleaning quote from REMA² Group in Woburn, MA.",
    headline: "Cleaning for your spaces.", accent: "Support for your operation.",
    lead: "Commercial cleaning, post-construction cleanup and property turnover support for businesses and contractors in Massachusetts and New Hampshire. REMA² is based in Woburn, MA, with cleaning services and workforce support built around an agreed scope.",
    scopeTitle: "Define the clean you need.",
    scopeIntro: "Different spaces call for different work. Tell us about the property, areas to be cleaned, current condition and access schedule so we can discuss the cleaning tasks and frequency.",
    services: [
      ["Commercial cleaning", "Cleaning support for business spaces and recurring accounts. Identify the areas, surfaces and working hours that matter to your operation."],
      ["Post-construction cleaning", "Cleanup following construction work, with tasks and timing coordinated around your project. Describe the condition of the space and the areas that need attention."],
      ["Turnover & deep cleaning", "Cleaning for changes in occupancy and spaces that need a more detailed scope. Share the property condition, areas to cover and target completion date."],
      ["Recurring cleaning support", "Discuss repeat visits or supplemental cleaning workers for an existing operation. Frequency, responsibilities and the work to be covered are agreed together."],
    ],
    planningTitle: "A clearer request means a clearer quote.",
    planning: ["Property city and state", "Type of space and approximate size", "Areas, surfaces and current condition", "One-time or recurring cleaning", "Preferred schedule and access requirements"],
    steps: [
      ["Describe the space.", "Share the location, property type, approximate size, condition and areas you want cleaned."],
      ["Review tasks & frequency.", "We discuss the cleaning scope, access, schedule and pricing, including whether the request is one-time or recurring."],
      ["Coordinate the service.", "Agree on responsibilities and communication for the cleaning work. Discuss any field documentation needed for a managed service."],
    ],
    faqs: [
      ["Do you offer one-time and recurring cleaning?", "Yes. Requests can cover a one-time cleanup, turnover, deep cleaning or recurring commercial cleaning. Share the scope and frequency you need."],
      ["Can you help after construction or renovation?", "Yes. REMA² offers post-construction cleaning. Include the project location, areas to be cleaned, current condition and the date the space will be ready for cleaning."],
      ["Can I request workers for my own cleaning operation?", "Yes. You can discuss supplemental workforce support or a cleaning service executed by REMA². Tell us which approach you need so responsibilities can be defined."],
      ["What information is needed for a cleaning quote?", "Send the city and state, type and approximate size of the space, cleaning tasks, frequency and preferred schedule. Access and property condition also help us review the request."],
    ],
    requestTitle: "Request a cleaning quote.",
    requestPlaceholder: "Describe the space, approximate size, condition, areas to clean and any access requirements.",
  },
  "landscaping": {
    name: "Landscaping",
    title: "Landscaping & Landscape Support in MA & NH | REMA² Group",
    description: "Landscaping, maintenance, installation and seasonal workforce support in Massachusetts and New Hampshire. Discuss your outdoor project with REMA² Group in Woburn, MA.",
    headline: "Landscaping support.", accent: "From upkeep to projects.",
    lead: "REMA² provides landscaping services and supplemental landscape crews for businesses, contractors and property projects in Massachusetts and New Hampshire. From recurring upkeep to seasonal demand, we discuss the work, schedule and coordination your outdoor operation needs.",
    scopeTitle: "Support for outdoor work.",
    scopeIntro: "Tell us about the outdoor areas, current condition and the result you need. We review the tasks and timing to distinguish recurring maintenance, an installation project or additional workers for your own crew.",
    services: [
      ["Landscape maintenance", "Support for ongoing outdoor upkeep within an agreed scope. Describe the areas, tasks and frequency needed for your property or account."],
      ["Landscape installation", "Field support and service execution for landscape installation projects. Share the planned work, site condition, materials and coordination needs."],
      ["Seasonal crew support", "Supplemental labor for busy periods and changing landscape workloads. Request workers for a project, recurring operation or seasonal assignment."],
      ["Hardscapes & outdoor projects", "Discuss hardscape and outdoor living work as part of your project request. The tasks, materials, responsibilities and schedule are reviewed before work is agreed."],
    ],
    planningTitle: "Tell us about your outdoor space.",
    planning: ["Project city and state", "Areas to maintain or improve", "Current condition and planned work", "Materials, access and site requirements", "Project deadline or recurring schedule"],
    steps: [
      ["Share the outdoor scope.", "Describe the property, areas, current condition and the maintenance or installation work you need."],
      ["Discuss the approach.", "We review whether you need extra workers or service execution, then discuss responsibilities, availability and pricing."],
      ["Plan the field work.", "Coordinate access, materials and communication around the agreed work and schedule."],
    ],
    faqs: [
      ["Do you provide landscaping services or just workers?", "REMA² offers both landscaping service execution and supplemental workforce support. Tell us whether you need a service or additional people for an existing operation."],
      ["Can I request recurring landscape maintenance?", "Yes. Describe the outdoor areas, maintenance tasks and preferred frequency. We review the recurring scope and scheduling with you."],
      ["Do you support hardscapes and outdoor living projects?", "Yes. These services can be discussed as part of your outdoor project. Include the planned work, site location, materials and target timeline so we can review the scope."],
      ["Can you help during seasonal workload peaks?", "Yes. Supplemental landscape crews can be requested for seasonal demand and special projects. The number of workers and start date are discussed based on your needs and availability."],
    ],
    requestTitle: "Plan your landscaping work.",
    requestPlaceholder: "Describe the outdoor areas, maintenance or installation tasks, materials and site access.",
  },
  "property-services": {
    name: "Property Services",
    title: "Property Maintenance & Field Services in MA & NH | REMA² Group",
    description: "Property cleanup, exterior maintenance, snow and ice support and recurring field services in Massachusetts and New Hampshire. Request a quote from REMA² Group.",
    headline: "Property services.", accent: "Keep the work coordinated.",
    lead: "Property cleanup, exterior maintenance and recurring field support for businesses, contractors and property operations in Massachusetts and New Hampshire. Based in Woburn, MA, REMA² helps you define the tasks and coordinate the people needed for the work.",
    scopeTitle: "Practical support for your property.",
    scopeIntro: "Property work can be a one-time cleanup, a seasonal request or a recurring account. Start with the areas and tasks you need covered so the service, schedule and responsibilities can be agreed.",
    services: [
      ["Property cleanup", "Field support for property cleanup within an agreed scope. Describe the areas, current condition and work that needs attention."],
      ["Exterior maintenance", "Support for recurring exterior upkeep and specific maintenance tasks. Share the property type, access requirements and frequency you need."],
      ["Snow & ice support", "Discuss snow removal and ice-related work for your property or field operation. Include the areas to cover, access requirements and timing so scope and scheduling can be agreed for your property."],
      ["Recurring field operations", "Coordinate workforce and service needs for an ongoing property account. Managed REMA² operations can include field documentation and progress reporting."],
    ],
    planningTitle: "Define what needs attention.",
    planning: ["Property city and state", "Areas and maintenance tasks", "Current condition and access details", "One-time, seasonal or recurring scope", "Preferred schedule and coordination needs"],
    steps: [
      ["Describe the property needs.", "Send the location, property type, areas to cover and the cleanup or maintenance tasks you need completed."],
      ["Set responsibilities & timing.", "We discuss workforce needs, service execution, availability and pricing before agreeing to the assignment."],
      ["Coordinate the account.", "Plan access and communication for the work. Discuss documentation and reporting needs for recurring or managed operations."],
    ],
    faqs: [
      ["Do you handle one-time and recurring property work?", "Yes. Requests can cover a specific cleanup, exterior maintenance, seasonal needs or recurring field operations. Describe the tasks and preferred frequency."],
      ["Do you provide snow and ice services?", "Yes. Snow and ice support is part of our offer. Contact us to discuss the location, scope and scheduling; availability and service terms need to be confirmed for each request."],
      ["Can cleaning and landscaping be part of a property request?", "Yes. REMA² also offers cleaning and landscaping services. Tell us the different tasks your property needs so each part of the scope can be reviewed."],
      ["Can I request property support in New Hampshire?", "Yes. REMA² serves Massachusetts and New Hampshire from its Woburn, MA base. Include the property's city and state when requesting a quote."],
    ],
    requestTitle: "Discuss your property needs.",
    requestPlaceholder: "Describe the property, cleanup or maintenance tasks, condition and access requirements.",
  },
};
